# Site settings
title:          Caracol DSA
description:    "Degrowth Caucus DSA site built using Jekyll and Github pages"
baseurl:        ""
url:            "https://CaracolDSA.github.io"

# Google Analytics
google_analytics: 

# Author
author:
  name:         Caracol DSA üêå
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         